sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  # build docker images
  - ./build.sh
  - docker tag justmaho/todo-proxy:latest registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    # push to dockerhub & heroku
    docker push justmaho/todo-proxy;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:push web --app $HEROKU_APP_NAME;
    heroku container:release web --app $HEROKU_APP_NAME;
  on:
    branch: master

notifications:
  slack: 26781ba0e95527698bc9f92d8f96cdd4ed193da5