defaultEntryPoints = ["http"]
logLevel = "DEBUG"

[traefikLog]
  filePath = "/traefik.log"
  format   = "json"

[entryPoints]
  [entryPoints.http]
    address = ":80" # will be overriden
  [entryPoints.traefik]
    address = ":8080"
    compress = true

[api]
  dashboard = true
  entryPoint = "traefik"

[frontends]
  [frontends.frontend1]
  backend = "backend1"
  
  [frontends.frontend2]
  backend = "backend2"
    [frontends.frontend2.routes.test_1]
      rule = "Path:/todos"
  
  [frontends.traefikAPI]
    backend = "traefik"
    [frontends.traefikAPI.routes.traefikAPI]
      rule = "PathPrefixStrip:/traefik"
  
[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "https://maho-todo-client.herokuapp.com/"
  [backends.backend2]
    [backends.backend2.servers.server1]
    url = "https://maho-todo-api.herokuapp.com/"
  [backends.traefik]
    [backends.traefik.servers.traefik]
      url = "http://localhost:8080"
